Package.swift, Sources/LLBBuildSystem/BuildEngine.swift, Sources/LLBBuildSystem/BuildEngineContext.swift, Sources/LLBBuildSystem/Function.swift, Sources/LLBBuildSystem/FunctionDelegate.swift, Sources/LLBBuildSystemTestHelpers/TestBuildEngine.swift, Tests/LLBBuildSystemTests/LLBBuildEngineTests.swift
This PR adds 4 commits that were required to add easy test support for the build system engine.
1: Adds support for dynamic resolution of build functions
2: Adds abstract LLBBuildFunction for a build specific interface
3: Refactor engine context into a protocol for easier usage
4: Adds basic test for the build system engine
The tests for now are super simple and could be implemeneted in the llbuild2 core engine instead, and as the CAS pieces start appearing, we'll be making use of those instead.
=> Refactor code to make adding tests easier

Package.swift, Sources/LLBRETool/Options.swift, Sources/LLBRETool/retool.swift, Sources/LLBUtil/CAS/FileBackedCASDatabase.swift, Sources/Tools/retool/CAS.swift, Sources/Tools/retool/Capabilities.swift, Sources/Tools/retool/main.swift, Sources/Tools/retool/misc.swift
This adds an implementation for file-backed CAS database that isn't
particularly efficient but useful for performing tests. This also adds
support for writing and reading to file-backed CAS using `retool cas`
subtool.
The cas subtool only operates on the file-backed CAS right now but that
can be evolved over time as we implement more CAS databases.
=> Add FileBackedCASDatabase

Protos/BuildSystem/Evaluation/artifact_owner.proto, Protos/BuildSystem/Evaluation/rule_evaluation.proto, Sources/LLBBuildSystem/FunctionMap.swift, Sources/LLBBuildSystem/Functions/Evaluation/Artifact.swift, Sources/LLBBuildSystem/Functions/Evaluation/EvaluatedTarget.swift, Sources/LLBBuildSystem/Functions/Evaluation/RuleEvaluation.swift, Sources/LLBBuildSystem/Functions/Execution/Action.swift, Sources/LLBBuildSystem/Generated/BuildSystem/Evaluation/artifact_owner.pb.swift, Sources/LLBBuildSystem/Generated/BuildSystem/Evaluation/rule_evaluation.pb.swift, Sources/LLBBuildSystem/Rules/RuleContext.swift, Tests/LLBBuildSystemTests/ArtifactTests.swift, Tests/LLBBuildSystemTests/RuleEvaluationTests.swift
This change ensures that static writes happen before action serialization, so that the artifacts have a chance to be updated before they're serialized.
Also, moves the actions into the value for rule evaluation, since that has a stable key during the evaluation of the function and should be cached at the moment the artifacts expand them
=> Fix upload of static writes and actions into the CAS to ensure it happens after artifact updates

Examples/GameOfLife/Sources/GameOfLife/Configuration/Configuration.swift, Examples/GameOfLife/Sources/GameOfLife/Functions/Generation.swift, Sources/LLBBuildSystem/Functions/Execution/ActionID.swift, Sources/LLBSupport/Futures/EventualResultsCache.swift, Sources/LLBSupport/Futures/FutureDeduplicator.swift, Sources/llbuild2/Core/Engine.swift, Sources/llbuild2/Core/KeyDependencyGraph.swift, Tests/LLBBuildSystemTests/BuildEngineTests.swift, Tests/LLBBuildSystemTests/ConfigurationTests.swift
- Make LLBKey essentially 'Hashable'
- Remove SHA256 digest usage in LLBKey
- Refactor engine to sit on top of EventualResultsCache
=> Refactor engine key usage

Sources/LLBBuildSystem/BuildKey.swift, Sources/LLBBuildSystem/Function.swift, Sources/LLBBuildSystem/Functions/Evaluation/Configuration.swift, Sources/llbuild2/Core/Engine.swift, Sources/llbuild2/EngineProtocol/AnySerializable.swift
This allows clients of llbuild2 to decide whether they want to use the raw function APIs or a more elaborate API that allows for caching of previously computed keys from a database.
=> Add LLBTypedCachedFunction implementation to engine core

Sources/LLBBuildSystem/Functions/Evaluation/Artifact.swift, Sources/LLBBuildSystem/Rules/RuleContext.swift
...also make Label.asRoot public as it's useful for clients
=> Add Artifact.sourceDirectory convenience method

Sources/llbuild2/Core/Engine.swift, Sources/llbuild2/Core/KeyDependencyGraph.swift
Make it efficient by keeping track only active edges (value of key still not determined) instead of keeping track and searching every edge ever recorded.
=> [Engine] Make dependency graph cycle detection more efficient

Sources/llbuild2fx/Coding.swift, Sources/llbuild2fx/Key.swift, Sources/llbuild2fx/Value.swift, Sources/llbuild2fx/WrappedDataID.swift
Rather than publishing non-threadsafe coder instances, allocate new coders as needed, and only publish the hashing function needed for key definitions.
=> Use separate coder instances

Sources/llbuild2fx/Delegate.swift, Sources/llbuild2fx/FunctionCache.swift, Sources/llbuild2fx/FunctionInterface.swift, Sources/llbuild2fx/Value.swift, Sources/llbuild2fx/WrappedDataID.swift
This avoids errors that print with arbitrary addresses, and removes some unused cases.
=> Ensure errors have stable names

Sources/llbuild2fx/SpawnProcess.swift
Re https://github.com/apple/swift-llbuild2/pull/133#discussion_r768118814
=> Rename `runLater` to `runCancellable`

Sources/llbuild2fx/Coding.swift, Sources/llbuild2fx/FunctionInterface.swift, Sources/llbuild2fx/Value.swift, Sources/llbuild2fx/Versioning.swift
To invalidate fine-grained portions of the cache, we need to be able to decode the persisted cache paths.
=> Publish types required for cache introspection

Sources/llbuild2fx/Coding.swift
Publishing the types doesn't do much good without also having `public` initializers.
=> Publish initializers for coders

Sources/llbuild2fx/Engine.swift, Sources/llbuild2fx/Executor.swift, Sources/llbuild2fx/FunctionInterface.swift, Sources/llbuild2fx/Stats.swift, Tests/llbuild2fxTests/EngineTests.swift
This also removes `public` access to the `Context`'s `FXExecutor`, instead funneling through the `FXFunctionInterface` to do the bookkeeping.
=> Add stats for tracking in-flight evaluations

Sources/llbuild2fx/FunctionInterface.swift, Sources/llbuild2fx/Key.swift
This means we'll also get stats for top-level keys, not just requested keys.
=> Move key stats to wrap `compute()` instead of `request()`

Sources/llbuild2fx/TreeMaterialization.swift
This fixes an issue where process execution would fail because the outputs were deleted before they could be imported.
=> Only remove directory after future completes

Sources/llbuild2fx/Key.swift
We're still seeing `llbuild2fx.(unknown context at $...).FXFunction<...>.Error.FXValueComputationError`.
=> Make `FXFunction` internal to fix errors

Sources/LLBBuildSystemUtil/LocalExecutor.swift
* Removes compiler warning about `is` operation being always false.
* The code did not match the comment in the first place.
=> Avoid wrapping error twice

Sources/llbuild2fx/SpawnProcess.swift
Upgrading from `private` to `internal` means we won't have addresses in error messages.
We were catching errors in the wrong order, so it looked like imports _always_ failed, despite also succeeding, which was super confusing.
=> Fix process spawning errors

Sources/llbuild2fx/TreeMaterialization.swift
This is more generally useful than just in the implementation of `TreeMaterialization`.
=> Publish `withTemporaryDirectory()`

Sources/llbuild2fx/Deadline.swift, Tests/llbuild2fxTests/DeadlineTests.swift
This avoids
~~~~
Fatal error: Double value cannot be converted to Int64 because the result would be greater than Int64.max
~~~~
=> Avoid crash when converting distant future date

Sources/llbuild2fx/FunctionInterface.swift, Sources/llbuild2fx/Key.swift, Sources/llbuild2fx/WrappedDataID.swift
- Fix cache key prefix memoization
- Avoid double hashing SingleDataIDValue's
- Bypass command line args encoder for hinted keys
- Defer calculation of logDescription until actually needed for
unexpressed dependency errors
=> FX performance improvements

Sources/llbuild2/Core/Engine.swift, Sources/llbuild2fx/Key.swift
Adopt recomputation by default in the FX engine.
rdar://89755290
=> Allow TypedCachingFunctions to recompute on cache failures

Sources/llbuild2fx/FunctionInterface.swift, Sources/llbuild2fx/SpawnProcess.swift
An attempt to debug a suspected precondition failure in Foundation: https://github.com/apple/swift-corelibs-foundation/blob/7ff84365bf8aa4406fa948c1a353a354fd696002/Sources/Foundation/Process.swift#L1088-L1089
=> Add action execution logs

Sources/llbuild2fx/SpawnProcess.swift
We don't need this anymore, and I'm going to add another case to `RuntimeValue`.
=> Remove support for Swift 5.4

Sources/llbuild2fx/Diagnostics.swift, Sources/llbuild2fx/SpawnProcess.swift
If we're going to kill a spawned process because it exceeded its timeout, it's useful to have diagnostics to later tell us why, e.g. if the process was hanging.
=> Gather diagnostics before killing spawned processes

Sources/LLBBuildSystemUtil/LocalExecutor.swift, Sources/LLBCommands/NinjaBuildTool.swift, Tests/LLBNinjaTests/NinjaBuildTests.swift
NinjaBuild now requires a "workingDirectory" argument. The default from the deprecated initializer was "/" so this PR just specifies that value directly to avoid the warning.
=> Fix deprecation warnings

Sources/llbuild2fx/Key.swift, Sources/llbuild2fx/Value.swift
It has been very difficult or even impossible to determine why a requested key was not found in the cache, e.g., when re-running a build with a few changes. Only the key information reflected in the InternalValue.cachePath was recorded. This change adds a reference in every InternalValue to the full JSON-encoded key for that value. With this, you can do things like comparing two builds to see exactly what differs in their requested keys.
This is implemented by encoding each key as JSON in the CAS and then adding a CAS reference as the first element in the refs for an InternalValue. Note that this is an incompatible change in the encoding of InternalValue that needs to be versioned appropriately.
=> Record full keys for llbuild2fx InternalValues

Sources/llbuild2fx/Value.swift
Given a cached value, this function provides access to the encoded key associated with that value.
=> Add FXEncodedKeyID function to access the new encoded key info

Sources/llbuild2fx/Key.swift, Sources/llbuild2fx/Value.swift
We don't yet have enough versioning in place to safely go ahead with my previous changes in #177 and #178. Changing the values associated with existing keys may be a problem if the old values still exist in a database where they are not versioned. Maybe we can come back and try this again later.
=> Revert changes to record and access full keys for llbuild2fx InternalValues

Sources/llbuild2fx/KeyConfiguration.swift, Sources/llbuild2fx/Versioning.swift
This should be used sparingly, if at all, as it will be the
most frequent source of cache invalidation. It is primarily useful
in FXKeys that need to pass a subset of the configuration to some external
system, without knowing which of those keys are reasonable to forward.
=> Allow prefix-matching in config keys.

Package.swift
SwiftPM complains that this package dependency is unused, so remove it.
=> Remove unused swift-nio dependency

Sources/LLBBuildSystemUtil/LocalExecutor.swift, Sources/Tools/llcastool/misc.swift, Tests/llbuild2Tests/FunctionCacheTests.swift
Hello there!
I was just getting started and tinkering with llbuild2, and noticed there are `AbsolutePath` deprecation warnings, so I cleaned them up:
- `AbsolutePath: ExpressibleByArgument` — if the argument is not a valid path, the initializer will return `nil`.
- `LocalExecutor` — the `fullInputPath` is already an `AbsolutePath`, so we can just pass it to `.export`, without copying it with `.init`, right?
- `FunctionCacheTests` — since that's in unit tests, and the argument defaults to `/tmp`, it's probably okay to `try!` here?
Tried `swift build` and `swift test` locally, and things seem to work fine.
I hope this is useful. Not trying to waste anyone's time with small PRs, I'm here to learn.
=> Use throwing AbsolutePath initializers to fix deprecation warnings

Package.resolved, Package.swift, Sources/llbuild2/Core/Engine.swift, Sources/llbuild2/Support/Tracing.swift, Sources/llbuild2fx/Key.swift
I’d like to extend llbuild2’s Context datatype with a `tracer` attribute that returns an optional `Tracer`.
This way keys will have a modern and unified way to start/end spans, without being coupled into a particular tracing technology.
⚠️ Warning: `startSpan` calls itself in an infinite recursion. (some bug where they try to use protocol extensions to provide default value) We should submit a PR to swift-distributed-tracing for a fix. Meanwhile this is the llbuild2fx PR. As long as we keep  `ctx.tracer = nil` in prod we will not hit the swift-distributed-tracing bug.
=> rdar://139536238 (Add swift-distributed-tracing to llbuild2fx)

Sources/llbuild2/Core/Engine.swift, Sources/llbuild2fx/Engine.swift
The LLBEventualResultsCache has a partialResultExpiration parameter with a default of 300 seconds, but some clients may want to set a different value.
=> Add a partialResultExpiration parameter to LLBEngine and FXBuildEngine

Sources/llbuild2fx/Action.swift, Sources/llbuild2fx/Executor.swift, Sources/llbuild2fx/FunctionInterface.swift, Sources/llbuild2fx/Key.swift, Sources/llbuild2fx/LocalExecutor.swift, Sources/llbuild2fx/NullExecutor.swift, Sources/llbuild2fx/Ruleset.swift, Sources/llbuild2fx/Versioning.swift
- Add action dependencies specification and enforcement
- Add new, simpler `spawn` call for actions
- Add stub mechanism for collecting requirements from action instances
- Deprecate `execute` (and associated `perform`) in favor of expecting the FXExecutor to resolve how to execute the `run` method
=> Action execution adjustments

Sources/llbuild2fx/Action.swift, Sources/llbuild2fx/Key.swift, Sources/llbuild2fx/TaskCancellationRegistry.swift, Tests/llbuild2fxTests/SpawnProcessTests.swift
This allows clients to cancel unstructured tasks that are created when we bridge from NIO to Swift Concurrency.
=> Add a TaskCancellationRegistry to cancel unstructured tasks

Sources/llbuild2fx/SpawnProcess.swift
Allows clients to read the immutable properties. This will allow clients to provide alternative implementation of SpawnProcess using the FXExecutor protocol, which is useful for unit testing.
=> [SpawnProcess] Expose immutable properties
