apple/swift-llbuild2

- Docs/retool.md
- Package.resolved
- Package.swift
- Sources/LLBRETool/retool.swift
- Sources/Tools/retool/main.swift
This is intended to be a low-level development/debugging tool for
interacting with the remote execution services.
> Add skeleton for retool

- .gitmodules
- Package.swift
- Sources/CBLAKE3/blake3.c
- Sources/CBLAKE3/blake3_avx2.c
- Sources/CBLAKE3/blake3_avx512.c
- Sources/CBLAKE3/blake3_impl.h
- Sources/CBLAKE3/blake3_sse41.c
- Sources/CBLAKE3/include/blake3.h
- Sources/LLBUtil/CAS/Blake3DataID.swift
- Sources/LLBUtil/CAS/InMemoryCASDatabase.swift
- Sources/llbuild2/CAS/Object.swift
- Sources/llbuild2/Support/ByteBuffer.swift
- Tests/LLBUtilTests/CAS/InMemoryCASDatabaseTests.swift
- Also adds BLAKE3 implementation of DataID
> Add InMemoryCASDatabase

- Docs/index.md
A few things jumped out to me so I thought I'd help for the next reader.  Thx!
> fixed some typos.

- Sources/LLBRETool/retool.swift
- Sources/LLBUtil/CAS/FileBackedCASDatabase.swift
- Sources/Tools/retool/CAS.swift
This shows great performance wins w/ the minimal testing I did.
Very rough numbers when reading and writing a 200 mb file:
Read:
TSC: 1.1s
NIO: 0.2s
Write
TSC: 0.8s
NIO: 0.3s
> [FileBackedCAS] Adopt NIO's non-blocking IO

- Sources/llbuild2/Core/Engine.swift
- Sources/llbuild2/Core/KeyDependencyGraph.swift
- Tests/llbuild2Tests/EngineTests.swift
- Tests/llbuild2Tests/KeyDependencyGraphTests.swift
Very basic cycle detection engine but that should hopefully help us in the short-medium term.
> Add cycle detection to llbuild2's Engine

- Protos/BuildSystem/Execution/action.proto
- Protos/BuildSystem/Execution/action_execution.proto
- Sources/LLBBuildSystem/Functions/Evaluation/Artifact.swift
- Sources/LLBBuildSystem/Functions/Execution/Action.swift
- Sources/LLBBuildSystem/Functions/Execution/ActionExecution.swift
- Sources/LLBBuildSystem/Generated/BuildSystem/Execution/action.pb.swift
- Sources/LLBBuildSystem/Generated/BuildSystem/Execution/action_execution.pb.swift
- Sources/LLBBuildSystem/Rules/RuleContext.swift
- Sources/LLBCASFileTree/CASFSClient.swift
- Tests/LLBBuildSystemTests/RuleEvaluationTests.swift
The test is commented out because it surfaced an error in the artifact -> artifact owner logic, need to rethink how that is implemented to prevent the issue from appearing
> Add support for tree merging for rule evaluation

- Sources/LLBBuildSystem/BuildKey.swift
- Sources/LLBCAS/Object.swift
- Sources/llbuild2/Core/Engine.swift
- Sources/llbuild2/EngineProtocol/AnySerializable.swift
- Sources/llbuild2/FunctionCache/InMemoryFunctionCache.swift
- Provides simple in memory implementation
- Fills out CAS object round trip for cached values
> Add function cache protocol

- Sources/LLBBuildSystemUtil/LocalExecutor.swift
This allows correctly ingesting the file type automatically (plainText,
executable) and makes it a little easier on the clients to handle the
outputs.
> [LocalExecutor] Consistently use CASTree for ingesting outputs

- Sources/LLBBuildSystemUtil/LocalExecutor.swift
We need a proper build events API but this is good in the mean term.
> [LocalExecutor] Add a trivial delegate to report progress

- Sources/LLBBuildSystem/Functions/Evaluation/RuleEvaluation.swift
- Sources/LLBBuildSystem/Rules/RuleContext.swift
This will allow rule implementations to use the function interface for
evaluating functions.
> [LLBBuildSystem] Expose function interface in rule context

- Package.swift
- Sources/llbuild2fx/Action.swift
- Sources/llbuild2fx/Coding.swift
- Sources/llbuild2fx/CommandLineArgsCoder.swift
- Sources/llbuild2fx/Delegate.swift
- Sources/llbuild2fx/Engine.swift
- Sources/llbuild2fx/Executor.swift
- Sources/llbuild2fx/FunctionCache.swift
- Sources/llbuild2fx/FunctionInterface.swift
- Sources/llbuild2fx/Key.swift
- Sources/llbuild2fx/Reëxport.swift
- Sources/llbuild2fx/Value.swift
- Sources/llbuild2fx/Versioning.swift
- Sources/llbuild2fx/WrappedDataID.swift
- Tests/llbuild2fxTests/EngineTests.swift
The FX engine is a rather different take on the providing a build system
interface on top of the llbuild2 core engine.  Far less Bazel inspired
in comparison to LLBBuildSystem, the FX engine is lighter weight and
potentially more approachable.
> Add alternative FX build engine implementation

- Sources/llbuild2fx/Key.swift
This avoids revealing key details that are encoded as hashes, i.e. `FXSingleDataIDValue`.
> Encode keys used in errors

- Sources/llbuild2fx/SpawnProcess.swift
`FileHandle()` returns `nil` if the file doesn't already exist, and `Process` treats `nil` outputs as "inherit from the calling process."
> Create redirected output files

- Sources/llbuild2fx/TreeMaterialization.swift
Previously, only trees were supported, and privately at that.  But both are useful in general when implementing actions.
> Add materialization support for files

- Sources/llbuild2fx/SpawnProcess.swift
This avoids the need to fall back to a shell script merely to copy a portion of the input tree to the output tree.
> Add ability to pre-populate the output tree

- Sources/llbuild2fx/SpawnProcess.swift
Instead, the caller (key) will define the policy, especially as it affects caching.
> Remove `exit(0)` policy from `FXSpawnProcess`

- Sources/llbuild2fx/SpawnProcess.swift
This also lets you mix-and-match different kinds of values, i.e. `literal` _and_ `inputPath` in a single runtime value, like the `PATH` environment variable.
> Allow multiple values at runtime, e.g. search paths

- Sources/llbuild2fx/KeyConfiguration.swift
> Fix quadratic behavior in KeyConfiguration

- Sources/llbuild2/Core/Engine.swift
- Sources/llbuild2fx/Key.swift
- Tests/llbuild2fxTests/EngineTests.swift
This allows us to recover from certain types bugs shipped to production that mutated the live cache, if we know how to fix the cache entries.
> Allow FXKeys to have programmatic 'cache fixing' methods

- Sources/llbuild2fx/Key.swift
> Allow client to distinguish cache misses from other errors

- Sources/llbuild2fx/Key.swift
`InternalKey.{stableHashValue,cachePath}` are very expensive to create and yet they are used for `Dictionary` accesses which means they're called _a lot_, potentially under a lock.
It appears however that they only contain _static_ input data which means we can just calculate them once at `init` time and store them.
> InternalKey: calculate stableHashValue & cachePath once

- Sources/llbuild2fx/TreeMaterialization.swift
- Sources/llbuild2fx/WrappedDataID.swift
- Add async materializer methods for FXFileID and FXTreeID
> Require FXTreeMaterializer to be async
